jobs:
  build:
    docker:
      - image: antonono/projetcicd:projetcicd
        auth:
          username: $DOCKER_LOGIN  # can specify string literal values
          password: $DOCKER_MDP
    steps:
      - run:
           name: Antoninbuild
           command: docker run -p 8080:8080 -t antonono/projetcicd:projetcicd

    jobs:
      - node/test:
          version: 13.11.0

