version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      # - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            ls
            docker build ./dockerfile -t node_app
      - run:
          name: Run tests
          command: |
            docker run --name temp -d -p 8888:8080 node_app 
            sleep 10
            npm test
      - run:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_MDP
            docker tag node_app antonono/node_app
            docker push antonono/node_app
