jobs:
  build:
    docker:
      - image: antonono/projetcicd:projetcicd
        auth:
          username: $DOCKER_LOGIN  # can specify string literal values
          password: $DOCKER_MDP
    steps:
      - run:
          name: test
          command: npm test

